### ISSUE TITLE
Missing usages

### ISSUE THREAD

**Issue by zhengj2007** [VEuPathDB-ontology/VEuPathDB-ontology#44]
According to OBO Foundry [principle 9](http://obofoundry.org/principles/fp-009-users.html), we should specify the users of the VEuPathDB ontology.

OBO Foundry principle 9: "The ontology developers should document that the ontology is used by multiple independent people or organizations." Examples and other details, please check page: http://obofoundry.org/principles/fp-009-users.html

Here are the format and information we need to provide:
```
user: https://veupathdb.org
description: Eukaryotic Pathogen, Host & Vector Genomics Resource (VEuPathDB) 
type: annotation
examples:
    - url: a URL pointed to a VEuPathDB term 
      description: annotation ...
```
